[package]
name = "file-organizer"
version = "2.0.0"
edition = "2024"

[dependencies]
gpui = "0.2.2"
gpui-component = "0.4.0"
anyhow = "1.0"
notify = "8.2.0"
crossbeam-channel = "0.5.15"
async-channel = "2.5.0"
dirs = "6.0.0"
chrono = "0.4.45"
open = "5.4.1"

[profile.dev]
split-debuginfo = "unpacked"
debug = 0 
strip = true

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_System_LibraryLoader", "Win32_Graphics_Gdi", "Win32_System_Threading"] }
